# infra/kustomize/overlays/dev/infra/namespace.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: engenox-system
  labels:
    app.kubernetes.io/name: engenox-system
    app.kubernetes.io/part-of: engenox
    environment: dev