steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/engenox-stage/postgres-age/engenox-postgres:17.5-age1.6-pgv0.8', '-f', 'Dockerfile.postgres.age', '.']
images: ['us-central1-docker.pkg.dev/engenox-stage/postgres-age/engenox-postgres:17.5-age1.6-pgv0.8']