apiVersion: v1
kind: Pod
metadata:
  name: debug-shell
  namespace: cnpg-system
spec:
  serviceAccountName: cnpg-manager
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"
  containers:
  - name: debug-shell
    image: ghcr.io/cloudnative-pg/cloudnative-pg:1.24.0
    command: ["/bin/sh", "-c", "sleep 300"]
  restartPolicy: Never