receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'mimir'
          static_configs:
            - targets: ['mimir:9010']
        - job_name: 'loki'
          static_configs:
            - targets: ['loki:3100']

exporters:
  prometheusremotewrite:
    endpoint: http://mimir:9009/api/v1/push
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [tempo, logging]
    metrics:
      receivers: [otlp, prometheus]
      exporters: [prometheusremotewrite, logging]
    logs:
      receivers: [otlp]
      exporters: [loki, logging]
