server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 1m
  max_block_bytes: 1073741824

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /data/traces

overrides:
  defaults:
    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: engenox-local
