# infra/kustomize/overlays/dev/observability/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - grafana.yaml
  - mimir.yaml
  - loki.yaml
  - tempo.yaml
  - dashboards.yaml
  - promtail.yaml
  - otel-collector-config.yaml
  - otel-collector.yaml
  - service-monitors.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: engenox
      environment: dev

patches:
  - target:
      kind: Deployment
    path: tolerations-patch.yaml
  - target:
      kind: StatefulSet
    path: tolerations-patch.yaml
  - target:
      kind: DaemonSet
    path: tolerations-patch.yaml