steps:
# Build and push action (Go)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/engenox-stage/services/action:latest'
    - '-f'
    - 'services/action/Dockerfile'
    - '--build-arg'
    - 'BUILDKIT_INLINE_CACHE=1'
    - '.'
  env:
    - 'DOCKER_BUILDKIT=1'
images:
  - 'us-central1-docker.pkg.dev/engenox-stage/services/action:latest'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'