steps:
# Build and push decision using Cloud Build Docker
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--platform=linux/amd64'
    - '-t'
    - 'us-central1-docker.pkg.dev/engenox-stage/services/decision:latest'
    - '-f'
    - 'services/decision/Dockerfile'
    - '.'
images:
  - 'us-central1-docker.pkg.dev/engenox-stage/services/decision:latest'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'