apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: engenox

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - services.yaml
  - deployments.yaml
  - ingress.yaml
  - web.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: engenox
